### ISSUE TITLE
App doesn't load on web

### ISSUE THREAD

**Issue by wottpal** [Jesway/flutter_translate#36] opened 2020-03-07 16:12 UTC
Has your project web-support? I assumed it as it is a "web" project on pub.dev but I didn't get it to work 😞 The app doesn't seem to start and stays white in Chrome. I've even reproduced it with your example project:

```
flutter channel dev
flutter upgrade
flutter config --enable-web
cd example
flutter create .
flutter run -d chrome
```

Cheers, Dennis

**Comment by bratan** [comment] 2020-03-10 08:17
@wottpal - Sorry but it doesn't work for web, only mobile for now.

Duplicate of #24

**Closed as completed by bratan** 2020-03-10 08:17 UTC
Labels: duplicate
